builds:
  - binary: terraform-provider-ovm
    goos:
      - darwin
      - linux
    goarch:
      - amd64
    env:
      - CGO_ENANBLED=0
sign:
  artifacts: checksum
  args: ["-u", "bnal@ba78.me", "--output", "${signature}", "--detach-sign", "${artifact}"]

snapshot:
  # Allows you to change the name of the generated snapshot
  # Default is `SNAPSHOT-{{.ShortCommit}}`.
  name_template: SNAPSHOT-{{.Commit}}

checksum:
  # You can change the name of the checksums file.
  # Default is `{{ .ProjectName }}_{{ .Version }}_checksums.txt`.
  name_template: "{{ .ProjectName }}_checksums.txt"

  # Algorithm to be used.
  # Accepted options are sha256, sha512, sha1, crc32, md5, sha224 and sha384.
  # Default is sha256.
  algorithm: sha256

release:
  prerelease: auto

changelog:
  # could either be asc, desc or empty
  # Default is empty
  sort: asc
  filters:
    # commit messages matching the regexp listed here will be removed from
    # the changelog
    # Default is empty
    exclude:
      - '^docs:'
      - '^ci:'